// webapp1/resources/js/pages/welcome.tsx
import { Head, Link, usePage } from '@inertiajs/react';
import { dashboard, login, register } from '@/routes';
import posts from '@/routes/posts';
import { Text, Container, Section } from '@radix-ui/themes';

export default function Welcome() {
    const { auth } = usePage().props;

    return (
        <>
            <Head title="Welcome" />
            <section className="flex min-h-screen flex-col items-center bg-[#FDFDFC]  text-[#1b1b18]  dark:bg-[#0a0a0a]">
                <header className="border-b-2 border-black-400 border-b-black-400 mb-6 w-full flex justify-center">
                    <div
                        id="nav-container"
                        className=" w-full max-w-[335px] text-sm not-has-[nav]:hidden lg:max-w-4xl flex justify-between items-center"
                    >
                        <Text weight={"bold"} wrap="wrap" className="text-lg">Posty</Text>
                        <nav className="flex items-center justify-end gap-4">
                            {auth.user ? (
                                <Link
                                    href={dashboard()}
                                    className="inline-block rounded-sm border border-[#19140035] px-5 py-1.5 text-sm leading-normal text-[#1b1b18] hover:border-[#1915014a] dark:border-[#3E3E3A] dark:text-[#EDEDEC] dark:hover:border-[#62605b]"
                                >
                                    Dashboard
                                </Link>
                            ) : (
                                <>

                                    <Link
                                        href={login()}
                                        className="inline-block rounded-sm border border-transparent px-5 py-1.5 text-sm leading-normal text-[#1b1b18] hover:border-[#19140035] dark:text-[#EDEDEC] dark:hover:border-[#3E3E3A]"
                                    >
                                        Login
                                    </Link>
                                    <Link
                                        href={register()}
                                        className="inline-block px-5 py-1.5 text-sm leading-normal text-[#1b1b18] hover:border-[#1915014a] dark:border-[#3E3E3A] dark:text-[#EDEDEC] dark:hover:border-[#62605b]"
                                    >
                                        Register
                                    </Link>
                                </>

                            )}
                            <Link href={posts.list()}>
                                Posts
                            </Link>
                        </nav>

                    </div>
                </header>
                <h2>Post whatever you want</h2>
                <Container>
                    <Section>
                        
                    </Section>
                </Container>
            </section>
        </>
    );
}

// webapp3/resources/js/pages/Welcome.vue
<script setup lang="ts">
import { Head, Link } from "@inertiajs/vue3";
import { dashboard, login } from "@/routes";
import { register } from "@/routes";
import { ref } from "vue";
import NavBarDefault from "@/components/NavBarDefault.vue";

const count = ref(0);

const increment = () => count.value++;
</script>

<template>
  <Head title="Welcome">
    <link rel="preconnect" href="https://rsms.me/" />
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
  </Head>
  <div
    class="flex min-h-screen flex-col items-center bg-[#FDFDFC] p-6 text-[#1b1b18] lg:justify-center lg:p-8 dark:bg-[#0a0a0a]"
  >
    <NavBarDefault />
    <div
      class="flex w-full justify-center opacity-100 transition-opacity duration-750 lg:grow starting:opacity-0"
    >
      <main
        class="flex w-full max-w-[335px] flex-col overflow-hidden rounded-lg lg:max-w-4xl"
      >
        <h1 class="text-2xl font-bold mb-6 text-center">Testing out vue features</h1>
        <section class="mb-3">
          <hgroup class="mb-2">
            <h2 class="font-sans text-xl font-bold">Count</h2>
            <p>Testing out the @click event to see how it updates state</p>
          </hgroup>
          <button @click="increment" class="bg-teal-400 block p-2 border text-white rounded-md hover:bg-teal-600 cursor-pointer">
            increment count
          </button>
          {{ count }}
        </section>

        <section></section>
        <section></section>
        <section></section>
        <section></section>
      </main>
    </div>
    <div class="hidden h-14.5 lg:block"></div>
  </div>
</template>
